### PR TITLE
Created a few simple and straightforward color sort methods

### PR DESCRIPTION
**Pull request by hanzhi713**
Also applied multi-threading to speed up downloads of head images. It will be able to resume downloading even if the process stops abruptly.

Also, I'll probably add new sorting methods later.

### CODE REVIEW

**Comment by T-K-233** [comment]
THIS IS BRILLIANT!

**Comment by T-K-233** [comment]
THIS IS BRILLIANT!

**Comment by T-K-233** [comment]
THIS IS EXCELLENT!!!!
Thanks a lot

**Comment by hanzhi713** [comment]
You're welcome

**Comment by hanzhi713** [comment]
The PR seems to have a bug

**Pull request merged**
